version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: diassindicoprofissional
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
